FROM node:16-alpine

WORKDIR '/app'

COPY package.json .

RUN npm install

# Not needed locally since volumes are pointed to local with docker-compose
# Enable for prod AND CI CD
COPY . .

CMD ["npm", "run", "start"]